# Generated by Django 4.2.13 on 2024-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('caption_title', models.CharField(blank=True, max_length=100)),
                ('caption_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
