# Generated by Django 4.2.13 on 2024-06-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_alter_carouselitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselitem",
            name="text_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="carouselitem",
            name="title_link",
            field=models.URLField(blank=True),
        ),
    ]
